services:
  app:
    build: .
    container_name: ambulance-api
    ports:
      - "8080:8080"
    environment:
      PORT: "8080"
      POSTGRES_DSN: "host=postgres port=5432 user=postgres password=postgres dbname=ambulance_db sslmode=disable"
      REDIS_ADDR: "redis:6379"
      REDIS_PASSWORD: ""
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: ambulance-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ambulance_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: ambulance-redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    restart: unless-stopped

volumes:
  pgdata:
  redisdata:
